/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.scientificcalculatorswing;

/**
 *
 * @author Dasun Wickramasooriya
 */
public class ScientificCalculator extends javax.swing.JFrame {

    /**
     * Creates new form ScientificCalculator
     */
    public ScientificCalculator() {
        initComponents();
        
    }
    
    double num1,num2,result;
    String opr;
    
    public void enable(){
        textFieldIn.setEnabled(true);
        buttonOn.setEnabled(false);
       buttonOff.setEnabled(true);
        
        button0.setEnabled(true);
        button1.setEnabled(true);
        button2.setEnabled(true);
        button3.setEnabled(true);
        button4.setEnabled(true);
        button5.setEnabled(true);
        button6.setEnabled(true);
        button7.setEnabled(true);
        button8.setEnabled(true);
        button9.setEnabled(true);
        buttonAdd.setEnabled(true);
        buttonB.setEnabled(true);
        buttonClr.setEnabled(true);
        buttonCos.setEnabled(true);
        buttonCosh.setEnabled(true);
        buttonCube.setEnabled(true);
        buttonDecimal.setEnabled(true);
        buttonDiv.setEnabled(true);
        buttonEquals.setEnabled(true);
        buttonExp.setEnabled(true);
        buttonFrac.setEnabled(true);
        buttonLog.setEnabled(true);
        buttonMulti.setEnabled(true);
        buttonPow.setEnabled(true);
        buttonR.setEnabled(true);
        buttonSign.setEnabled(true);
        buttonSin.setEnabled(true);
        buttonSinh.setEnabled(true);
        buttonSqr.setEnabled(true);
        buttonR.setEnabled(true);
        buttonTan.setEnabled(true);
        buttonTanh.setEnabled(true);
        buttonSub.setEnabled(true);
        buttonPrec.setEnabled(true);
        
    }
    
    public void disable(){
        textFieldIn.setEnabled(false);
        buttonOn.setEnabled(true);
       buttonOff.setEnabled(false);
        
        button0.setEnabled(false);
        button1.setEnabled(false);
        button2.setEnabled(false);
        button3.setEnabled(false);
        button4.setEnabled(false);
        button5.setEnabled(false);
        button6.setEnabled(false);
        button7.setEnabled(false);
        button8.setEnabled(false);
        button9.setEnabled(false);
        buttonAdd.setEnabled(false);
        buttonB.setEnabled(false);
        buttonClr.setEnabled(false);
        buttonCos.setEnabled(false);
        buttonCosh.setEnabled(false);
        buttonCube.setEnabled(false);
        buttonDecimal.setEnabled(false);
        buttonDiv.setEnabled(false);
        buttonEquals.setEnabled(false);
        buttonExp.setEnabled(false);
        buttonFrac.setEnabled(false);
        buttonLog.setEnabled(false);
        buttonMulti.setEnabled(false);
        buttonPow.setEnabled(false);
        buttonR.setEnabled(false);
        buttonSign.setEnabled(false);
        buttonSin.setEnabled(false);
        buttonSinh.setEnabled(false);
        buttonSqr.setEnabled(false);
        buttonR.setEnabled(false);
        buttonTan.setEnabled(false);
        buttonTanh.setEnabled(false);
        buttonSub.setEnabled(false);
        buttonPrec.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpOnOff = new javax.swing.ButtonGroup();
        textFieldIn = new javax.swing.JTextField();
        buttonOn = new javax.swing.JRadioButton();
        buttonOff = new javax.swing.JRadioButton();
        buttonR = new javax.swing.JButton();
        buttonFrac = new javax.swing.JButton();
        buttonPow = new javax.swing.JButton();
        buttonCube = new javax.swing.JButton();
        buttonSqr = new javax.swing.JButton();
        buttonSign = new javax.swing.JButton();
        buttonSin = new javax.swing.JButton();
        buttonExp = new javax.swing.JButton();
        buttonTan = new javax.swing.JButton();
        buttonCos = new javax.swing.JButton();
        buttonTanh = new javax.swing.JButton();
        buttonCosh = new javax.swing.JButton();
        buttonSinh = new javax.swing.JButton();
        buttonLog = new javax.swing.JButton();
        buttonPrec = new javax.swing.JButton();
        buttonClr = new javax.swing.JButton();
        buttonB = new javax.swing.JButton();
        buttonAdd = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        buttonSub = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        buttonMulti = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        buttonDiv = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        buttonEquals = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        buttonDecimal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scientific Calculator");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        textFieldIn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textFieldIn.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnGrpOnOff.add(buttonOn);
        buttonOn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonOn.setText("ON");
        buttonOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOnActionPerformed(evt);
            }
        });

        btnGrpOnOff.add(buttonOff);
        buttonOff.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonOff.setText("OFF");
        buttonOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOffActionPerformed(evt);
            }
        });

        buttonR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonR.setText("R");
        buttonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRActionPerformed(evt);
            }
        });

        buttonFrac.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonFrac.setText("1/x");
        buttonFrac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFracActionPerformed(evt);
            }
        });

        buttonPow.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonPow.setText("x^y");
        buttonPow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPowActionPerformed(evt);
            }
        });

        buttonCube.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonCube.setText("x^3");
        buttonCube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCubeActionPerformed(evt);
            }
        });

        buttonSqr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonSqr.setText("x^2");
        buttonSqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSqrActionPerformed(evt);
            }
        });

        buttonSign.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonSign.setText("+/-");
        buttonSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSignActionPerformed(evt);
            }
        });

        buttonSin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonSin.setText("sin");
        buttonSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSinActionPerformed(evt);
            }
        });

        buttonExp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonExp.setText("exp");
        buttonExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExpActionPerformed(evt);
            }
        });

        buttonTan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonTan.setText("tan");
        buttonTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTanActionPerformed(evt);
            }
        });

        buttonCos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonCos.setText("cos");
        buttonCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCosActionPerformed(evt);
            }
        });

        buttonTanh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonTanh.setText("tanh");
        buttonTanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTanhActionPerformed(evt);
            }
        });

        buttonCosh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonCosh.setText("cosh");
        buttonCosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCoshActionPerformed(evt);
            }
        });

        buttonSinh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonSinh.setText("sinh");
        buttonSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSinhActionPerformed(evt);
            }
        });

        buttonLog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonLog.setText("log");
        buttonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogActionPerformed(evt);
            }
        });

        buttonPrec.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonPrec.setText("%");
        buttonPrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrecActionPerformed(evt);
            }
        });

        buttonClr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonClr.setText("Clr");
        buttonClr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClrActionPerformed(evt);
            }
        });

        buttonB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonB.setText("B");
        buttonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBActionPerformed(evt);
            }
        });

        buttonAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonAdd.setText("+");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        button7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button7.setText("7");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        button8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button8.setText("8");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });

        button9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button9.setText("9");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });

        buttonSub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonSub.setText("-");
        buttonSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubActionPerformed(evt);
            }
        });

        button6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button6.setText("6");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        buttonMulti.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonMulti.setText("*");
        buttonMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMultiActionPerformed(evt);
            }
        });

        button4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button4.setText("4");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button5.setText("5");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        buttonDiv.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonDiv.setText("/");
        buttonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivActionPerformed(evt);
            }
        });

        button3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button3.setText("3");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button1.setText("1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button2.setText("2");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        buttonEquals.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonEquals.setText("=");
        buttonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEqualsActionPerformed(evt);
            }
        });

        button0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button0.setText("0");
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });

        buttonDecimal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonDecimal.setText(".");
        buttonDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDecimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldIn)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonOn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonOff))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(buttonSign, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonSqr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonCube, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonPow, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonFrac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonExp, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonSin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonCos, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonTan, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonLog, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonCosh, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonTanh, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonPrec, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(buttonClr, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonB, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonSub, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(buttonDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(buttonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(textFieldIn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonOn)
                            .addComponent(buttonOff))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonR, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonExp, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonTan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonFrac, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonLog, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCosh, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonTanh, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonPow, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonPrec, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonClr, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonB, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonCube, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSub, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonSqr, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSign, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
       textFieldIn.setText(textFieldIn.getText()+"0");
    }//GEN-LAST:event_button0ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
    textFieldIn.setText(textFieldIn.getText()+"1");
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
    textFieldIn.setText(textFieldIn.getText()+"2");    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
    textFieldIn.setText(textFieldIn.getText()+"3");
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
    textFieldIn.setText(textFieldIn.getText()+"4");
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
    textFieldIn.setText(textFieldIn.getText()+"5");
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
    textFieldIn.setText(textFieldIn.getText()+"6");
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
     textFieldIn.setText(textFieldIn.getText()+"7");
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
    textFieldIn.setText(textFieldIn.getText()+"8");
    }//GEN-LAST:event_button8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
    textFieldIn.setText(textFieldIn.getText()+"9");
    }//GEN-LAST:event_button9ActionPerformed

    private void buttonDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDecimalActionPerformed
    textFieldIn.setText(textFieldIn.getText()+".");

    }//GEN-LAST:event_buttonDecimalActionPerformed

    private void buttonClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClrActionPerformed
    textFieldIn.setText("");
    }//GEN-LAST:event_buttonClrActionPerformed

    private void buttonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBActionPerformed
    String backSpace = null;
        if (textFieldIn.getText().length() > 0) {
            StringBuilder sb = new StringBuilder(textFieldIn.getText());
            sb.deleteCharAt(textFieldIn.getText().length()-1);
            backSpace = sb.toString();
            textFieldIn.setText(backSpace);
        }
    
    }//GEN-LAST:event_buttonBActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
    num1 = Double.parseDouble(textFieldIn.getText());
    
    textFieldIn.setText("");
    
    opr = "+";
    
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubActionPerformed
    num1 = Double.parseDouble(textFieldIn.getText());
    
    textFieldIn.setText("");
    
    opr = "-";
    }//GEN-LAST:event_buttonSubActionPerformed

    private void buttonMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMultiActionPerformed
    num1 = Double.parseDouble(textFieldIn.getText());
    
    textFieldIn.setText("");
    
    opr = "*";    }//GEN-LAST:event_buttonMultiActionPerformed

    private void buttonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDivActionPerformed
    num1 = Double.parseDouble(textFieldIn.getText());
    
    textFieldIn.setText("");
    
    opr = "/";
    }//GEN-LAST:event_buttonDivActionPerformed

    private void buttonPrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrecActionPerformed
    num1 = Double.parseDouble(textFieldIn.getText());
    
    textFieldIn.setText("");
    
    opr = "%";
    }//GEN-LAST:event_buttonPrecActionPerformed

    private void buttonEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEqualsActionPerformed
    num2 = Double.parseDouble(textFieldIn.getText());
    
        if (opr == "+") {
            result = num1+num2;
            textFieldIn.setText(Double.toString(result));
        }else if (opr == "-") {
            result = num1-num2;
            textFieldIn.setText(Double.toString(result));
        }else if (opr == "*") {
            result = num1*num2;
            textFieldIn.setText(Double.toString(result));
        }else if (opr == "/") {
            result = num1/num2;
            textFieldIn.setText(Double.toString(result));
        }else if (opr == "%") {
            result = num1%num2;
            textFieldIn.setText(Double.toString(result));
        }else if (opr == "^") {
            result = Math.pow(num1,num2);
            textFieldIn.setText(Double.toString(result));
        }
    }//GEN-LAST:event_buttonEqualsActionPerformed

    private void buttonSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSinActionPerformed
     double t = Math.sin(Double.parseDouble(textFieldIn.getText()));
     
     textFieldIn.setText((""));
     textFieldIn.setText(textFieldIn.getText()+t);
     
    }//GEN-LAST:event_buttonSinActionPerformed

    private void buttonCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCosActionPerformed
    double t = Math.cos(Double.parseDouble(textFieldIn.getText()));
     
     textFieldIn.setText((""));
     textFieldIn.setText(textFieldIn.getText()+t);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCosActionPerformed

    private void buttonTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTanActionPerformed
     double t = Math.tan(Double.parseDouble(textFieldIn.getText()));
     
     textFieldIn.setText((""));
     textFieldIn.setText(textFieldIn.getText()+t);
    }//GEN-LAST:event_buttonTanActionPerformed

    private void buttonSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSinhActionPerformed
    double t = Math.sinh(Double.parseDouble(textFieldIn.getText()));
     
     textFieldIn.setText((""));
     textFieldIn.setText(textFieldIn.getText()+t);    }//GEN-LAST:event_buttonSinhActionPerformed

    private void buttonCoshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCoshActionPerformed
     double t = Math.cosh(Double.parseDouble(textFieldIn.getText()));
     
     textFieldIn.setText((""));
     textFieldIn.setText(textFieldIn.getText()+t);
    }//GEN-LAST:event_buttonCoshActionPerformed

    private void buttonTanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTanhActionPerformed
     double t = Math.tanh(Double.parseDouble(textFieldIn.getText()));
     
     textFieldIn.setText((""));
     textFieldIn.setText(textFieldIn.getText()+t);
    }//GEN-LAST:event_buttonTanhActionPerformed

    private void buttonLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogActionPerformed
     double t = Math.log(Double.parseDouble(textFieldIn.getText()));
     
     textFieldIn.setText((""));
     textFieldIn.setText(textFieldIn.getText()+t);
    }//GEN-LAST:event_buttonLogActionPerformed

    private void buttonExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExpActionPerformed
     double t = Math.exp(Double.parseDouble(textFieldIn.getText()));
     
     textFieldIn.setText((""));
     textFieldIn.setText(textFieldIn.getText()+t);
    }//GEN-LAST:event_buttonExpActionPerformed

    private void buttonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRActionPerformed
     double t = Math.sqrt(Double.parseDouble(textFieldIn.getText()));
     
     textFieldIn.setText((""));
     textFieldIn.setText(textFieldIn.getText()+t);
    }//GEN-LAST:event_buttonRActionPerformed

    private void buttonFracActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFracActionPerformed
     double t = 1/(Double.parseDouble(textFieldIn.getText()));
     
     textFieldIn.setText((""));
     textFieldIn.setText(textFieldIn.getText()+t);
    }//GEN-LAST:event_buttonFracActionPerformed

    private void buttonSqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSqrActionPerformed
     double t =Double.parseDouble(textFieldIn.getText());
     
     t=t*t;
     textFieldIn.setText((""));
     textFieldIn.setText(textFieldIn.getText()+t);
    }//GEN-LAST:event_buttonSqrActionPerformed

    private void buttonCubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCubeActionPerformed
    double t =Double.parseDouble(textFieldIn.getText());
     
     t=t*t*t;
     textFieldIn.setText((""));
     textFieldIn.setText(textFieldIn.getText()+t);
    }//GEN-LAST:event_buttonCubeActionPerformed

    private void buttonPowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPowActionPerformed
    num1 = Double.parseDouble(textFieldIn.getText());
    
    textFieldIn.setText("");
    
    opr = "^";
    
    }//GEN-LAST:event_buttonPowActionPerformed

    private void buttonOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOnActionPerformed
    enable();
    }//GEN-LAST:event_buttonOnActionPerformed

    private void buttonOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOffActionPerformed
    disable();
    }//GEN-LAST:event_buttonOffActionPerformed

    private void buttonSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSignActionPerformed
    double t = Double.parseDouble(String.valueOf(textFieldIn.getText()));
    
    t = t*(-1);
    textFieldIn.setText(String.valueOf(t));
    }//GEN-LAST:event_buttonSignActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScientificCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScientificCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScientificCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScientificCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScientificCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrpOnOff;
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonB;
    private javax.swing.JButton buttonClr;
    private javax.swing.JButton buttonCos;
    private javax.swing.JButton buttonCosh;
    private javax.swing.JButton buttonCube;
    private javax.swing.JButton buttonDecimal;
    private javax.swing.JButton buttonDiv;
    private javax.swing.JButton buttonEquals;
    private javax.swing.JButton buttonExp;
    private javax.swing.JButton buttonFrac;
    private javax.swing.JButton buttonLog;
    private javax.swing.JButton buttonMulti;
    private javax.swing.JRadioButton buttonOff;
    private javax.swing.JRadioButton buttonOn;
    private javax.swing.JButton buttonPow;
    private javax.swing.JButton buttonPrec;
    private javax.swing.JButton buttonR;
    private javax.swing.JButton buttonSign;
    private javax.swing.JButton buttonSin;
    private javax.swing.JButton buttonSinh;
    private javax.swing.JButton buttonSqr;
    private javax.swing.JButton buttonSub;
    private javax.swing.JButton buttonTan;
    private javax.swing.JButton buttonTanh;
    private javax.swing.JTextField textFieldIn;
    // End of variables declaration//GEN-END:variables
}
